openapi: 3.0.0
info:
  title: Pizza Restaurant API
  version: 1.0.0
  description: RESTful API for a pizza restaurant

paths:
  /admin/pizzas:
    get:
      tags:
        - admin
      summary: Get all pizzas
      description: Returns a list of all pizzas in the menu
      responses:
        '200':
          description: List of pizzas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pizza'
      security:
        - basicAuth: []
    post:
      tags:
        - admin
      summary: Create a new pizza
      description: Creates a new pizza in the menu
      requestBody:
        description: Pizza object to be created
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pizza'
      responses:
        '201':
          description: Created pizza
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pizza'
        '422':
          description: Unprocessable Entity
      security:
        - basicAuth: []
  /admin/pizzas/{pizza_id}:
    get:
      tags:
        - admin
      summary: Get a pizza by ID
      description: Returns a single pizza by ID
      parameters:
        - name: pizza_id
          in: path
          description: ID of the pizza to retrieve
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Pizza object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pizza'
        '404':
          description: Pizza not found
      security:
        - basicAuth: []
    put:
      tags:
        - admin
      summary: Update a pizza by ID
      description: Updates a pizza by ID
      parameters:
        - name: pizza_id
          in: path
          description: ID of the pizza to update
          required: true
          schema:
            type: integer
      requestBody:
        description: Pizza object to be updated
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pizza'
      responses:
        '200':
          description: Updated pizza
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pizza'
        '404':
          description: Pizza not found
        '422':
          description: Unprocessable Entity
      security:
        - basicAuth: []
    delete:
      tags:
        - admin
      summary: Delete a pizza by ID
      description: Deletes a pizza by ID
      parameters:
        - name: pizza_id
          in: path
          description: ID of the pizza to delete
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: No content
        '404':
          description: Pizza not found
      security:
        - basicAuth: []

  /admin/pizzerias:
    get:
      tags:
        - admin
      summary: Get all pizzerias
      description: Returns a list of all pizzerias
      responses:
        '200':
          description: List of pizzerias
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pizzeria'
      security:
        - basicAuth: []
    post:
      tags:
        - admin
      summary: Create a new pizzeria
      description: Creates a new pizzeria
      requestBody:
        description: Pizzeria object to be created
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pizzeria'
      responses:
        '201':
          description: Created pizzeria
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pizzeria'
        '422':
          description: Unprocessable Entity
      security:
        - basicAuth: []

  /admin/pizzerias/{pizzeria_id}:
    get:
      tags:
        - admin
      summary: Get a pizzeria by ID
      description: Returns a single pizzeria by ID
      parameters:
        - name: pizzeria_id
          in: path
          description: ID of the pizzeria
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Pizzeria object
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Pizzeria'
        '404':
          description: Pizzeria not found
      security:
        - basicAuth: []
  /admin/pizzerias/{pizzeria_id}/pizzas:
    post:
      tags:
        - admin
      summary: Add pizza to pizzeria menu
      description: Adds a new pizza to the menu of a pizzeria
      parameters:
        - in: path
          name: pizzeria_id
          required: true
          description: ID of the pizzeria to add the pizza to
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PizzeriaPizza'
      responses:
        '201':
          description: The newly created pizza
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pizza'
        '404':
          description: Pizzeria not found
        '422':
          description: Unprocessable Entity
      security:
        - basicAuth: []
  /admin/pizzerias/{pizzeria_id}/pizzas/{pizza_id}:
    delete:
      tags:
        - admin
      summary: Remove pizza from pizzeria menu
      description: Removes a pizza from the menu of a pizzeria
      parameters:
        - in: path
          name: pizzeria_id
          required: true
          description: ID of the pizzeria to remove the pizza from
          schema:
            type: integer
        - in: path
          name: pizza_id
          required: true
          description: ID of the pizza to remove
          schema:
            type: integer
      responses:
        '204':
          description: Pizza removed successfully
        '404':
          description: Pizza тще ащгтв
      security:
        - basicAuth: []
  /guest/pizzas:
    get:
      tags:
        - guest
      summary: Get all pizzas for a guest
      description: Returns a list of all pizzas in the menu
      responses:
        '200':
          description: List of pizzas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pizza'
  /guest/pizzas/{pizza_name}:
    get:
      tags:
        - guest
      summary: Get a pizza by name for a guest
      description: Returns a single pizza by name
      parameters:
        - name: pizza_name
          in: path
          description: name of the pizza to retrieve
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Pizza object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pizza'
        '404':
          description: Pizza not found
  /guest/pizzerias:
    get:
      tags:
        - guest
      summary: Search for pizzerias by address or get all pizzerias for a guest
      description: Returns a list of pizzerias filtered by the specified address substring or a list of all pizzerias
      parameters:
        - name: search
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: List of pizzerias matching the search criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pizzeria'
        '404':
          description: Pizzeria not found
  /guest/pizzerias/{pizzeria_id}/pizzas/:
    get:
      tags:
        - guest
      summary: Get all pizzas for a guest in Pizzzeria by ID
      description: Returns a list of all pizzas in the menu
      parameters:
        - name: pizzeria_id
          in: path
          description: ID of the pizzeria
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: List of pizzas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pizza'
        '404':
          description: Pizzeria not found
components:
  schemas:
    Pizza:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        price:
          type: number
          format: float
        image_url:
          type: string
      required:
        - name
        - description
        - price
        - image_url

    Pizzeria:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        address:
          type: string
      required:
        - name
        - address

    PizzeriaPizza:
      type: object
      properties:
        pizzeria_id:
          type: integer
          format: int64
        pizza_id:
          type: integer
          format: int64
      required:
        - pizzeria_id
        - pizza_id

  securitySchemes:
    basicAuth:
      type: http
      scheme: basic


  parameters:
    pizzaId:
      name: id
      in: path
      description: ID of the pizza
      required: true
      schema:
        type: integer
        format: int64

    pizzeriaId:
      name: id
      in: path
      description: ID of the pizzeria
      required: true
      schema:
        type: integer
        format: int64

  responses:
    NotFound:
      description: Entity not found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string

    Unauthorized:
      description: Unauthorized request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string

    Forbidden:
      description: Forbidden request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string